- name: install nginx service
  hosts: web
  become: yes
  tasks:
  - name: installing nginx 
    ansible.builtin.dnf:
    name: nginx 
    state: latest
  - name: start nginx  and enable nginx
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

  
    
      
    

