- name: variable declarion using var files
  hosts: localhost
  vars_files:
  - vars.yaml 
  tasks:
  - name : calling var files
    ansible.builtin.debug:
     msg: "Hello {{Name}}  welcome to {{Course}} mastering"
