- name: variables values from user
  hosts: localhost
  vars_prompt:
  - name: NAME
    prompt: Please enter your name
    private: false
  - password: PASSWORD
    prompt: Please enter password
    private: true

  tasks:
  - name : reading values from user
    ansible.builtin.debug:
     msg: "Hello {{NAME}} , your Password is set to {{PASSWORD}}"
