- name: variables values from user
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your username
    private: false
  - name: PASSWORD
    prompt: Please enter your password
    private: true

  tasks:
  - name : reading values from user
    ansible.builtin.debug:
     msg: "Hello {{USERNAME}} , your Password is set to {{PASSWORD}}"
