- name: variable preference
  hosts: localhost
  vars:
     WISHES: "Happy learning from Play var"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: WISHES
    prompt: Please enter Wishes
    private: false
  tasks:
  - name: check preference
    #vars:
    # WISHES: "Happy learning from tasks var"
    ansible.builtin.debug:
      msg: "{{WISHES}}"

# 1. arguments
# 2. Task level
# 3. variable files
# 4. Prompt
# 5. Play level
# 6. inventory
# 7. role level