- name : conditions in ansible
  hosts: localhost
  become: true
  tasks:
  - name: using when condition 
    ansible.builtin.command: id expense
    ignore_errors: true


  - name: using when condition 
    ansible.builtin.command: useradd expense
  
  
  - name: print user info
    ansible.builtin.debug:
     msg: "Hello"



