- name : conditions in ansible
  hosts: localhost
  become: true
  tasks:
  - name: check whether user exist or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true


  - name: adding user if not exist 
    ansible.builtin.command: useradd expense

  - name: print user info
    ansible.builtin.debug:
     msg: "{{USER}}"  
  
  
  - name: print Hello
    ansible.builtin.debug:
     msg: "Hello"



