- name : default value
  hosts: localhost
  tasks:
  - name : assigning default value using filters
    ansible.builtin.debug:
     msg:  "Course is {{course | default('DevOps')}}"
     
- name : uppercase
  hosts: localhost
  tasks:
  - name : converting to uppercase
    ansible.builtin.debug:
     msg:  " devops | uppercase "
     
