- name : default value
  hosts: localhost
  tasks:
  - name : assigning default value using filters
    ansible.builtin.debug:
     msg:  "Course is {{course | default('DevOps')}}"
     
- name : usage of filter upper
  hosts: localhost
  vars:
    course: devops
  tasks:
  - name : converting to uppercase
    ansible.builtin.debug:
     msg:  " {{course | upper }} "

- name: usage of filter lower
  hosts: localhost 
  vars:
   course: DEVOPS
  tasks: 
  - name: converting to lowercase
    ansible.builtin.debug:
     msg: "{{course | lower }}"
        
- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 3, 4, 4, 5]
    names: ['devops', 'devops','aws']
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }} , {{ names | unique }}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [25, 35, 67, 89]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"

