- name: using loops in ansible
  hosts: localhost
  tasks:
  - name : looping through the list of items given
    ansible.builtin.debug:
     msg: " {{item}} is devops tool"
    loop: 
    - linux
    - ansible
    - devops
