- name: ansible loops 
  hosts: localhost
  become: yes
  tasks:
  - name : installing packges with ansible loops
    ansible.builtin.dnf:
     name: {{item}}
     state: latest
    loop: 
    - nginx
    - mysql
    - postfix
  
