- name : loops
  hosts: localhost
  become: yes
  tasks:
  - name: package management in ansible
    ansible.builtin.dnf:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'} # item
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'absent'}

